### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'requote'

### ISSUE THREAD

**Issue by chiwalfrm** [bitfinexcom/bitfinex-api-py#100]
#### Issue type
- [X] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
I am just following the QuickStart instructions and instantly get the error.

#### Steps to reproduce
$ cd bfxapi/examples/ws
$ python3 subscribe_trades_candles.py
Traceback (most recent call last):
  File "subscribe_trades_candles.py", line 5, in <module>
    from bfxapi import Client
  File "/home/vmware/.local/lib/python3.6/site-packages/bfxapi/__init__.py", line 6, in <module>
    from .client import Client
  File "/home/vmware/.local/lib/python3.6/site-packages/bfxapi/client.py", line 11, in <module>
    from .rest.bfx_rest import BfxRest
  File "/home/vmware/.local/lib/python3.6/site-packages/bfxapi/rest/bfx_rest.py", line 6, in <module>
    import aiohttp
  File "/home/vmware/.local/lib/python3.6/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import *  # noqa
  File "/home/vmware/.local/lib/python3.6/site-packages/aiohttp/client.py", line 16, in <module>
    from yarl import URL
  File "/home/vmware/.local/lib/python3.6/site-packages/yarl/__init__.py", line 1, in <module>
    from ._url import URL, cache_clear, cache_configure, cache_info
  File "/home/vmware/.local/lib/python3.6/site-packages/yarl/_url.py", line 58, in <module>
    @rewrite_module
  File "/home/vmware/.local/lib/python3.6/site-packages/yarl/_url.py", line 131, in URL
    _QUOTER = _Quoter(requote=False)
  File "yarl/_quoting.pyx", line 192, in yarl._quoting._Quoter.__init__
TypeError: __init__() got an unexpected keyword argument 'requote'

##### Additional Notes:
-

**Comment by itsdeka** [comment]
It works on my end. Please, can you confirm you are in a virtual environment with the libraries of requirements.txt?

**Comment by chiwalfrm** [comment]
I have all the pip libraries in requirements.txt.  All of my modules are same or higher versions:

eventemitter (0.2.0) *same*
asyncio (3.4.3) *same*
websockets (8.1) *higher*
pylint (2.6.0) *higher*
six (1.15.0) *higher*
pyee (8.1.0) *higher*
aiohttp (3.7.3) *higher*
isort (5.7.0) *higher*

this is on Ubuntu Desktop 18.04.2 LTS with latest updates.  Don't know what I am doing wrong.

**Comment by chiwalfrm** [comment]
Starting over: Did a fresh install of Ubuntu Desktop 18.04.2 LTS, downloaded and installed all OS updates.  Now it gets a new error.

vmware@vmware-virtual-machine:~/Downloads/bitfinex-api-py/bfxapi/examples/ws$ python3 subscribe_trades_candles.py 
Traceback (most recent call last):
  File "subscribe_trades_candles.py", line 8, in <module>
    logLevel='DEBUG'
  File "/home/vmware/.local/lib/python3.6/site-packages/bfxapi/client.py", line 26, in __init__
    ws_capacity=ws_capacity, create_event_emitter=create_event_emitter, *args, **kwargs)
  File "/home/vmware/.local/lib/python3.6/site-packages/bfxapi/websockets/bfx_websocket.py", line 168, in __init__
    super(BfxWebsocket, self).__init__(host, logLevel=logLevel, *args, **kwargs)
  File "/home/vmware/.local/lib/python3.6/site-packages/bfxapi/websockets/generic_websocket.py", line 80, in __init__
    self.events = create_ee()
  File "/home/vmware/.local/lib/python3.6/site-packages/bfxapi/websockets/generic_websocket.py", line 60, in _start_event_worker
    return EventEmitter(scheduler=asyncio.ensure_future)
TypeError: __init__() got an unexpected keyword argument 'scheduler'

**Comment by itsdeka** [comment]
It looks like you are trying with an old version of bitfinex-api-py.
As you can check at line 60 of generic_websocket.py, now there is AsyncIOEventEmitter instead of EventEmitter.
https://github.com/bitfinexcom/bitfinex-api-py/blob/master/bfxapi/websockets/generic_websocket.py#L59

Download latest version and I think it will work.

**Comment by chiwalfrm** [comment]
You are right, it is older version (1.1.8) because I used the "pip3 install bitfinex-api-py" command.  When will pip3 repository get the new version?  Otherwise this will just happen to everybody who is using the pip3 repository and doesn't clone the github

**Comment by chiwalfrm** [comment]
Now that I am on the latest version, i now have the following issue running the example code.  I made no changes to the python script except putting my API key and secret in.  But running it still returns an error.

vmware@ubuntu18042a:~/Downloads/bitfinex-api-py/bfxapi/examples/rest$ python3 get_authenticated_data.py
Traceback (most recent call last):
  File "get_authenticated_data.py", line 98, in <module>
    asyncio.get_event_loop().run_until_complete(t)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "get_authenticated_data.py", line 85, in run
    await log_wallets()
  File "get_authenticated_data.py", line 24, in log_wallets
    wallets = await bfx.rest.get_wallets()
  File "/usr/local/lib/python3.6/dist-packages/bitfinex_api_py-1.1.8-py3.6.egg/bfxapi/rest/bfx_rest.py", line 384, in get_wallets
  File "/usr/local/lib/python3.6/dist-packages/bitfinex_api_py-1.1.8-py3.6.egg/bfxapi/rest/bfx_rest.py", line 59, in post
  File "/usr/local/lib/python3.6/dist-packages/bitfinex_api_py-1.1.8-py3.6.egg/bfxapi/utils/auth.py", line 34, in generate_auth_headers
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by chiwalfrm** [comment]
ok to close this issue, I got it working
