### ISSUE TITLE
Exception on Python 3.9 

### ISSUE THREAD

**Issue by rokups** [bitfinexcom/bitfinex-api-py#106]
#### Issue type
- [x] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
```
  File "/home/rk/src/bfx/venv/lib/python3.9/site-packages/websockets/protocol.py", line 911, in write_frame
    with (yield from self._drain_lock):
TypeError: 'Lock' object is not iterable
```

#### Steps to reproduce
- Execute latest version on Python 3.9

##### Additional Notes:
- https://github.com/aaugustin/websockets/issues/760
- Issue is fixed by updating websockets module to latest version.

**Comment by itsdeka** [comment]
Thank you very much for reporting this issue.
I'll open a PR soon.

**Comment by itsdeka** [comment]
I tried to upgrade websockets to 8.1 and there are issues with running tests/ws/* files. Are you able to run those?

**Comment by rokups** [comment]
O didn't try tests, but there were some other warnings and backtesting live 
didn't work. But at least exceptions went away.

**Comment by imankulov** [comment]
Hey there! I can see that the issue has been fixed in c755d33d280432bbc9ade0b2bd17eb339eb43009. @itsdeka, I would appreciate if you could release a new version with the fix on PyPI. Thanks!

**Comment by itsdeka** [comment]
Thank you all, done @imankulov

**Comment by PsykotropyK** [comment]
Hello. 
I installed the package by cloning the repo & while the setup.py references websockets 8.1 and this is the version I have installed, I have the same issue. 
Complete stack trace is 

> Traceback (most recent call last):
  File "D:\Apps\Python\Python39\lib\site-packages\bitfinex_api_py-1.1.14-py3.9.egg\bfxapi\websockets\generic_websocket.py", line 143, in _run_socket
  File "D:\Apps\Python\Python39\lib\site-packages\bitfinex_api_py-1.1.14-py3.9.egg\bfxapi\websockets\bfx_websocket.py", line 477, in on_message
  File "D:\Apps\Python\Python39\lib\site-packages\bitfinex_api_py-1.1.14-py3.9.egg\bfxapi\websockets\bfx_websocket.py", line 208, in _ws_system_handler
  File "D:\Apps\Python\Python39\lib\site-packages\bitfinex_api_py-1.1.14-py3.9.egg\bfxapi\websockets\bfx_websocket.py", line 242, in _system_info_handler
  File "D:\Apps\Python\Python39\lib\site-packages\bitfinex_api_py-1.1.14-py3.9.egg\bfxapi\websockets\bfx_websocket.py", line 501, in on_open
  File "D:\Apps\Python\Python39\lib\site-packages\bitfinex_api_py-1.1.14-py3.9.egg\bfxapi\websockets\bfx_websocket.py", line 492, in _ws_authenticate_socket
  File "D:\Apps\Python\Python39\lib\site-packages\bitfinex_api_py-1.1.14-py3.9.egg\bfxapi\websockets\generic_websocket.py", line 56, in send
  File "D:\Apps\Python\Python39\lib\site-packages\websockets\protocol.py", line 467, in send
    yield from self.write_frame(True, OP_TEXT, data.encode('utf-8'))
  File "D:\Apps\Python\Python39\lib\site-packages\websockets\protocol.py", line 911, in write_frame
    with (yield from self._drain_lock):
TypeError: 'Lock' object is not iterable
