### ISSUE TITLE
WebSocket connection is closed code 1006

### ISSUE THREAD

**Issue by jonasbrami** [bitfinexcom/bitfinex-api-py#118]
When subscribing to any order book, I get this websocket errors very often:
`[BfxWebsocket] [ERROR] WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no re(ason`

(I am using wss://api.bitfinex.com/ws/2)

**Comment by slurpxbt** [comment]
Im gettring the same problem, usually or almost always happens midnight utc and then webcoscket doesn't resubscribe succesfully

I really don't know ho to fix this...I was trying to stop websooket on error but code bellow doen't disconnect the websocket 
also tried resubscribing but it doenn't work

@bfx.ws.on("error")
async def stop_ws()
     await bfx.ws.stop()

`[[1m[90mBfxWebsocket[0m[0m] [[91mERROR[0m] code = 1006 (connection closed abnormally [internal]), no reason
[[1m[90mBfxWebsocket[0m[0m] [[94mINFO[0m] Waiting 5 seconds before retrying...
[[1m[90mBfxWebsocket[0m[0m] [[94mINFO[0m] Reconnect attempt 1/5
[[1m[90mBfxWebsocket[0m[0m] [[94mINFO[0m] Websocket connected to wss://api-pub.bitfinex.com/ws/2
[[1m[90mBfxWebsocket[0m[0m] [[94mINFO[0m] {'event': 'info', 'version': 2, 'serverId': '028d5ea6-dbf1-49f2-9aed-605f72677161', 'platform': {'status': 1}}
[[1m[90mBfxWebsocket[0m[0m] [[94mINFO[0m] Websocket opened.
[[1m[90mBfxSubscriptionManager[0m[0m] [[94mINFO[0m] Subscribing to channel trades
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Python\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\Desktop\Python\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\live code\bitfinex\bfxapi\websockets\generic_websocket.py", line 99, in start_loop
    loop.run_until_complete(self._run_socket())
  File "C:\Users\Administrator\Desktop\Python\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Administrator\Desktop\live code\bitfinex\bfxapi\websockets\generic_websocket.py", line 143, in _run_socket
    await self.on_message(sId, message)
  File "C:\Users\Administrator\Desktop\live code\bitfinex\bfxapi\websockets\bfx_websocket.py", line 472, in on_message
    await self._ws_system_handler(socketId, msg)
  File "C:\Users\Administrator\Desktop\live code\bitfinex\bfxapi\websockets\bfx_websocket.py", line 207, in _ws_system_handler
    await self._WS_SYSTEM_HANDLERS[eType](socketId, msg)
  File "C:\Users\Administrator\Desktop\live code\bitfinex\bfxapi\websockets\bfx_websocket.py", line 268, in _system_error_handler
    self._emit('error', err_string)
  File "C:\Users\Administrator\Desktop\live code\bitfinex\bfxapi\websockets\generic_websocket.py", line 193, in _emit
    self.events.emit(event, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\Python\lib\site-packages\pyee\_base.py", line 116, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "C:\Users\Administrator\Desktop\Python\lib\site-packages\pyee\_base.py", line 86, in _emit_handle_potential_error
    raise error
TypeError: exceptions must derive from BaseException`



The biggest ptoblem is that try and except doens't intercept this exception just stops the datastream

code that gives me this error:

` try:
            bfx = Client(API_KEY="",API_SECRET="")
            @bfx.ws.on('connected')
            async def start():
                await bfx.ws.subscribe('trades', 'tBTCUSD')

            trades = []

            @bfx.ws.on('new_trade')
            def new_trade(trade):

                global trades # -------------------------
                
                price = trade["price"]
                size = trade["amount"]

                if size > 0:
                    side = "buy"  
                else:
                    side = "sell"
                
                ticker = "BTCUSD"
                trades.append([ticker,side,round(price,1),size]) 

            bfx.ws.run()
            main()`

 except Exception as e:
            traceback.print_exc()

thx for help

**Comment by itsdeka** [comment]
Thank you, I am investigating

**Comment by PsykotropyK** [comment]
@itsdeka I have the same issuem with the same asyncio exception raised. I thought it came from subscribing to too many things but I tried with 100 order book and it doesn't trigger neither 1006 nor asyncio.
Can it be that the error occurs when the rest of my app (i.e. what I trigger with a @bfx.ws.on('order_book_update')) blocks asyncio and generates anomalies as the websocket is pending?

**Comment by mrajancsr** [comment]
Did you find a solution to the problem?

**Comment by t0rrent** [comment]
listen for unwanted websocket closure then keep trying to reconnect until the connection is successful. you never know want kind of routine they have with their servers
