### ISSUE TITLE
Checksum Error for order_book for Funding

### ISSUE THREAD

**Issue by EUA** [bitfinexcom/bitfinex-api-py#19]
I change subscribe_orderbook.py to track BTC  interest by changing line 27 with:
`await bfx.ws.subscribe('book', 'fBTC')`
but get got such an error:

```
...
...
...
[BfxWebsocket] [DEBUG] [10614,[0.00008744,2,18,55.61031005]]
Book update: {'symbol': 'fBTC', 'data': [8.744e-05, 2, 18, 55.61031005]}
[BfxWebsocket] [DEBUG] [10614,"cs",-809501394]
[BfxWebsocket] [WARNING] Checksum orderbook invalid for 'fBTC'. Resetting subscription.
[BfxWebsocket] [DEBUG] {"event":"unsubscribed","status":"OK","chanId":10614}
[BfxWebsocket] [DEBUG] {"event":"subscribed","channel":"book","chanId":10615,"symbol":"fBTC","prec":"P0","freq":"F0","len":"25","currency":"BTC"}
Traceback (most recent call last):
  File "Fundbot.py", line 40, in <module>
    bfx.ws.run()
  File "/home/death/Desktop/BotTerest/bitfinex-api-py/bfxapi/websockets/GenericWebsocket.py", line 51, in run
    self.loop.run_until_complete(self._main(self.host))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/death/Desktop/BotTerest/bitfinex-api-py/bfxapi/websockets/GenericWebsocket.py", line 75, in _main
    await self._connect(host)
  File "/home/death/Desktop/BotTerest/bitfinex-api-py/bfxapi/websockets/GenericWebsocket.py", line 66, in _connect
    await self.on_message(message)
  File "/home/death/Desktop/BotTerest/bitfinex-api-py/bfxapi/websockets/BfxWebsocket.py", line 369, in on_message
    await self._ws_system_handler(msg)
  File "/home/death/Desktop/BotTerest/bitfinex-api-py/bfxapi/websockets/BfxWebsocket.py", line 151, in _ws_system_handler
    await self._WS_SYSTEM_HANDLERS[eType](msg)
  File "/home/death/Desktop/BotTerest/bitfinex-api-py/bfxapi/websockets/BfxWebsocket.py", line 195, in _system_subscribed_handler
    await self.subscriptionManager.confirm_subscription(data)
  File "/home/death/Desktop/BotTerest/bitfinex-api-py/bfxapi/websockets/SubscriptionManager.py", line 59, in confirm_subscription
    p_sub = self.pending_subscriptions[get_key]
KeyError: 'book_fBTC'
```

**Comment by Shrootzzz** [comment]
I am also having the same problem. How is the checksum for funding books calculated?

**Comment by JacobPlaster** [comment]
Thanks for reporting this, Ill take a look into it. For now you could disable the orderbook checksum validation by setting `manageOrderBooks=False` in the client constructor.

**Comment by djimmo** [comment]
Is the checksum for funding books working now? I read in the node code there were issues with backend sorting. Would be good to have this check to be sure local book is consistent.

```
// NOTE: Checksums are temporarily disabled for funding books, due to
//       invalid book sorting on the backend. This change is temporary
```
see https://github.com/bitfinexcom/bitfinex-api-node/blob/master/lib/transports/ws2.js#L644

I know this is the python repo, but the issue has to do with the Bitfinex backend, so I thought this is related :)

**Comment by JacobPlaster** [comment]
thanks @djimmo. @EUA can you confirm if you are still having the issue?

**Comment by Jay54520** [comment]
@JacobPlaster Still have this issue. I guess may because funding book have a additional field -- `period`.
```
[BfxWebsocket] [INFO] Websocket connected to wss://api-pub.bitfinex.com/ws/2
[BfxWebsocket] [DEBUG] {"event":"info","version":2,"serverId":"64aa234a-b16b-4ef8-9cb4-e31feca3ab25","platform":{"status":1}}
[BfxWebsocket] [INFO] {'event': 'info', 'version': 2, 'serverId': '64aa234a-b16b-4ef8-9cb4-e31feca3ab25', 'platform': {'status': 1}}
[BfxWebsocket] [INFO] Websocket opened.
[BfxSubscriptionManager] [INFO] Subscribing to channel book
[BfxWebsocket] [DEBUG] {"event":"conf","status":"OK","flags":131072}
[BfxWebsocket] [INFO] Enabled config flag CHECKSUM
[BfxWebsocket] [DEBUG] {"event":"subscribed","channel":"book","chanId":106275,"symbol":"fBTC","prec":"P0","freq":"F0","len":"25","currency":"BTC"}
[BfxWebsocket] [DEBUG] [106275,[[0.00008101,30,1,-1.18760596],[0.000081,15,1,-10],[0.000081,30,1,-0.1135],[0.00008002,30,1,-10],[0.00008001,30,2,-19.56218837],[0.00008,30,1,-0.1502],[0.00007,30,2,-0.2254],[0.00006888,30,1,-0.05],[0.000068,10,1,-8.99651326],[0.000065,30,1,-0.21],[0.000062,30,1,-3],[0.0000601,30,1,-0.05],[0.00006,30,1,-10],[0.0000595,7,1,-4.8008663],[0.0000595,30,3,-2.30072588],[0.000059,30,1,-0.06],[0.00005503,30,1,-0.1871],[0.00005053,30,1,-0.05],[0.00005,30,2,-20],[0.00004,30,1,-5],[0.0000361,30,1,-5.18],[0.000036,30,6,-6],[0.0000353,30,1,-0.07],[0.0000351,30,1,-0.4],[0.000035,30,4,-33.55],[0.00010248,2,1,0.02964941],[0.00010263,2,1,0.01195374],[0.00010425,2,1,0.01195374],[0.00010461,2,1,0.01258288],[0.0001047,2,1,0.08892933],[0.00010588,2,1,0.01195374],[0.00010633,2,1,0.01258288],[0.0001075,2,1,0.01195374],[0.00010804,2,1,0.01258288],[0.00010913,2,1,0.01195374],[0.00010976,2,1,0.01258288],[0.00011075,2,1,0.01195374],[0.00011147,2,1,0.01258288],[0.00011238,2,1,0.01195374],[0.00011319,2,1,0.01258288],[0.0001149,2,1,0.01258288],[0.00011662,2,1,0.01258288],[0.00011793,2,3,0.1872273],[0.000118,30,1,8],[0.00011847,2,1,0.05168149],[0.00011852,2,18,0.99624646],[0.00011852,4,1,0.006316],[0.00011853,2,1,0.02339125],[0.00011888,2,2,0.21070011],[0.00011912,2,1,0.006727]]]
Initial book: {'symbol': 'fBTC', 'data': [[8.101e-05, 30, 1, -1.18760596], [8.1e-05, 15, 1, -10], [8.1e-05, 30, 1, -0.1135], [8.002e-05, 30, 1, -10], [8.001e-05, 30, 2, -19.56218837], [8e-05, 30, 1, -0.1502], [7e-05, 30, 2, -0.2254], [6.888e-05, 30, 1, -0.05], [6.8e-05, 10, 1, -8.99651326], [6.5e-05, 30, 1, -0.21], [6.2e-05, 30, 1, -3], [6.01e-05, 30, 1, -0.05], [6e-05, 30, 1, -10], [5.95e-05, 7, 1, -4.8008663], [5.95e-05, 30, 3, -2.30072588], [5.9e-05, 30, 1, -0.06], [5.503e-05, 30, 1, -0.1871], [5.053e-05, 30, 1, -0.05], [5e-05, 30, 2, -20], [4e-05, 30, 1, -5], [3.61e-05, 30, 1, -5.18], [3.6e-05, 30, 6, -6], [3.53e-05, 30, 1, -0.07], [3.51e-05, 30, 1, -0.4], [3.5e-05, 30, 4, -33.55], [0.00010248, 2, 1, 0.02964941], [0.00010263, 2, 1, 0.01195374], [0.00010425, 2, 1, 0.01195374], [0.00010461, 2, 1, 0.01258288], [0.0001047, 2, 1, 0.08892933], [0.00010588, 2, 1, 0.01195374], [0.00010633, 2, 1, 0.01258288], [0.0001075, 2, 1, 0.01195374], [0.00010804, 2, 1, 0.01258288], [0.00010913, 2, 1, 0.01195374], [0.00010976, 2, 1, 0.01258288], [0.00011075, 2, 1, 0.01195374], [0.00011147, 2, 1, 0.01258288], [0.00011238, 2, 1, 0.01195374], [0.00011319, 2, 1, 0.01258288], [0.0001149, 2, 1, 0.01258288], [0.00011662, 2, 1, 0.01258288], [0.00011793, 2, 3, 0.1872273], [0.000118, 30, 1, 8], [0.00011847, 2, 1, 0.05168149], [0.00011852, 2, 18, 0.99624646], [0.00011852, 4, 1, 0.006316], [0.00011853, 2, 1, 0.02339125], [0.00011888, 2, 2, 0.21070011], [0.00011912, 2, 1, 0.006727]]}
Book update: {'symbol': 'fBTC', 'data': [0.00011852, 2, 19, 1.30978966]}
[BfxWebsocket] [DEBUG] [106275,[0.00011852,2,19,1.30978966]]
[BfxWebsocket] [DEBUG] [106275,"cs",-1073884590]
[BfxWebsocket] [WARNING] Checksum orderbook invalid for 'fBTC'. Resetting subscription.
```
