### ISSUE TITLE
Python 3.10 Support

### ISSUE THREAD

**Issue by PLEXATIC** [bitfinexcom/bitfinex-api-py#204]
#### Issue type
- [x] bug
- [ ] missing functionality
- [ ] performance
- [x] feature request (possibly)

#### Brief description
The library does not work with python 3.10(.4)

#### Steps to reproduce
- Create environment using Python 3.10.4
- Install bitfinex-api-py (2.0.2)
- Run example code for authentication from docs:
```python
from bfxapi import Client
bfx = Client(
  API_KEY=<KEY>,
  API_SECRET=<SECRET>
)


@bfx.ws.on('authenticated')
async def submit_order(auth_message):
    print(auth_message)
bfx.ws.run()
```

##### Additional Notes:
Output:
Exception in thread Thread-3 (_start_new_async_socket):
Traceback (most recent call last):
  File "c:\Users\someUserName\anaconda3\envs\trader\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "c:\Users\someUserName\anaconda3\envs\trader\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\someUserName\anaconda3\envs\trader\lib\site-packages\bfxapi\websockets\generic_websocket.py", line 100, in _start_new_async_socket
    loop.run_until_complete(self._run_socket())
  File "c:\Users\someUserName\anaconda3\envs\trader\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "c:\Users\someUserName\anaconda3\envs\trader\lib\site-packages\bfxapi\websockets\generic_websocket.py", line 137, in _run_socket
    async with websockets.connect(self.host) as websocket:
  File "c:\Users\someUserName\anaconda3\envs\trader\lib\site-packages\websockets\legacy\client.py", line 604, in __aenter__
    return await self
  File "c:\Users\someUserName\anaconda3\envs\trader\lib\site-packages\websockets\legacy\client.py", line 622, in __await_impl__
    transport, protocol = await self._create_connection()
  File "c:\Users\someUserName\anaconda3\envs\trader\lib\asyncio\base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "c:\Users\someUserName\anaconda3\envs\trader\lib\asyncio\base_events.py", line 1107, in _create_connection_transport
    protocol = protocol_factory()
  File "c:\Users\someUserName\anaconda3\envs\trader\lib\site-packages\websockets\legacy\client.py", line 160, in __init__
    super().__init__(**kwargs)
  File "c:\Users\someUserName\anaconda3\envs\trader\lib\site-packages\websockets\legacy\protocol.py", line 154, in __init__
    self._drain_lock = asyncio.Lock(
  File "c:\Users\someUserName\anaconda3\envs\trader\lib\asyncio\locks.py", line 78, in __init__
    super().__init__(loop=loop)
  File "c:\Users\someUserName\anaconda3\envs\trader\lib\asyncio\mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Lock() since it is no longer necessary

**Comment by GlennOu66304** [comment]
Hey, simply upgrade your WebSocket to the latest version, then the error will gone:
```
python3 -m pip install --upgrade websockets
```
for the detailed explanation, you check this discussion in the WebSocket official 
Python 3.10 support (loop parameter was removed from Lock()) 
https://github.com/aaugustin/websockets/issues/916)](https://github.com/aaugustin/websockets/issues/916

**Comment by PLEXATIC** [comment]
Thanks, this worked for me
