### ISSUE TITLE
"TypeError: constraints must be a tuple" when importing bfxapi in Python 3.12.2

### ISSUE THREAD

**Issue by ipa-tys** [bitfinexcom/bitfinex-api-py#241]
Importing bfxapi in Python 3.12.2 gives the error shown below. 
Everything works fine in Python 3.11.8.

```
Python` 3.12.2 | packaged by Anaconda, Inc. | (main, Feb 27 2024, 11:35:17) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from bfxapi import Client, REST_HOST
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/bitcointrading/lib/python3.12/site-packages/bfxapi/__init__.py", line 1, in <module>
    from ._client import PUB_REST_HOST, PUB_WSS_HOST, REST_HOST, WSS_HOST, Client
  File "/opt/miniconda3/envs/bitcointrading/lib/python3.12/site-packages/bfxapi/_client.py", line 6, in <module>
    from bfxapi.websocket import BfxWebSocketClient
  File "/opt/miniconda3/envs/bitcointrading/lib/python3.12/site-packages/bfxapi/websocket/__init__.py", line 1, in <module>
    from ._client import BfxWebSocketClient
  File "/opt/miniconda3/envs/bitcointrading/lib/python3.12/site-packages/bfxapi/websocket/_client/__init__.py", line 1, in <module>
    from .bfx_websocket_client import BfxWebSocketClient
  File "/opt/miniconda3/envs/bitcointrading/lib/python3.12/site-packages/bfxapi/websocket/_client/bfx_websocket_client.py", line 18, in <module>
    from bfxapi.websocket._event_emitter import BfxEventEmitter
  File "/opt/miniconda3/envs/bitcointrading/lib/python3.12/site-packages/bfxapi/websocket/_event_emitter/__init__.py", line 1, in <module>
    from .bfx_event_emitter import BfxEventEmitter
  File "/opt/miniconda3/envs/bitcointrading/lib/python3.12/site-packages/bfxapi/websocket/_event_emitter/bfx_event_emitter.py", line 5, in <module>
    from pyee.asyncio import AsyncIOEventEmitter
  File "/opt/miniconda3/envs/bitcointrading/lib/python3.12/site-packages/pyee/__init__.py", line 34, in <module>
    from pyee.base import EventEmitter as EventEmitter
  File "/opt/miniconda3/envs/bitcointrading/lib/python3.12/site-packages/pyee/base.py", line 12, in <module>
    Handler = TypeVar(name="Handler", bound=Callable)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: constraints must be a tuple
```

**Comment by ipa-tys** [comment]
Ok, thanks @Davi0kProgramsThings!

**Comment by ipa-tys** [comment]
Ok, thanks @Davi0kProgramsThings!
