### ISSUE TITLE
Importing bfxapi results in a segfault

### ISSUE THREAD

**Issue by jazarija** [bitfinexcom/bitfinex-api-py#244]
## I'm submitting a...

- [x ] bug report;
- [ ] feature request;
- [ ] documentation change;

## What is the current behaviour?

When importing bfxapi, I get a segmentation fault
```
Python 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bfxap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'bfxap'
>>> import bfxapi
Segmentation fault (core dumped)
```

I've tried to isolate this issue by running different environments and different versions of the required libraries, but with no luck. Interestingly if I install the very latest beta version of Python 3.13 importing bfxapi raises exceptions

```
Python 3.13.0b2 (main, Jun  8 2024, 19:38:38) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bfxapi
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import bfxapi
  File "/home/azi/.local/lib/python3.13/site-packages/bfxapi/__init__.py", line 1, in <module>
    from ._client import PUB_REST_HOST, PUB_WSS_HOST, REST_HOST, WSS_HOST, Client
  File "/home/azi/.local/lib/python3.13/site-packages/bfxapi/_client.py", line 6, in <module>
    from bfxapi.websocket import BfxWebSocketClient
  File "/home/azi/.local/lib/python3.13/site-packages/bfxapi/websocket/__init__.py", line 1, in <module>
    from ._client import BfxWebSocketClient
  File "/home/azi/.local/lib/python3.13/site-packages/bfxapi/websocket/_client/__init__.py", line 1, in <module>
    from .bfx_websocket_client import BfxWebSocketClient
  File "/home/azi/.local/lib/python3.13/site-packages/bfxapi/websocket/_client/bfx_websocket_client.py", line 17, in <module>
    from bfxapi.websocket._connection import Connection
  File "/home/azi/.local/lib/python3.13/site-packages/bfxapi/websocket/_connection.py", line 18, in <module>
    _P = ParamSpec("_P")
  File "/usr/lib/python3/dist-packages/typing_extensions.py", line 1549, in __new__
    _set_default(paramspec, default)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/typing_extensions.py", line 1412, in _set_default
    type_param.__default__ = None
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: attribute '__default__' of 'typing.ParamSpec' objects is not writable
```

Any idea how to fix this one?

### Python version

Python 3.12.3 x64

**Comment by jazarija** [comment]
Interesting enough, if I update typing_extensions on Python 3.13.0b2 then I also incur a segfault

```
Python 3.13.0b2 (main, Jun  8 2024, 19:38:38) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bfxapi
Segmentation fault (core dumped)
```

**Comment by jazarija** [comment]
Hey there,

can confirm that bfxapi works on python3.11

```
Python 3.11.9 (main, Apr 27 2024, 21:16:11) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bfxapi
>>> 

```

What is the compatibility issue of switching to 3.12+?

**Comment by itsdeka** [comment]
Thank you @Davi0kProgramsThings
