### ISSUE TITLE
unexpected argument from bitfinex-api-py library

### ISSUE THREAD

**Issue by RomeoVir** [bitfinexcom/bitfinex-api-py#249]
I get an error of unexpected argument when i'm trying to submit an order.
The code i used (as readme example).

```python
from bfxapi import Client, REST_HOST

from bfxapi.types import Notification, Order

bfx = Client(
    rest_host=REST_HOST,
    api_key="<YOUR BFX API-KEY>",
    api_secret="<YOUR BFX API-SECRET>"
)

notification: Notification[Order] = bfx.rest.auth.submit_order(
    type="EXCHANGE LIMIT", symbol="tBTCUSD", amount=0.165212, price=30264.0)

order: Order = notification.data

if notification.status == "SUCCESS":
    print(f"Successful new order for {order.symbol} at {order.price}$.")

if notification.status == "ERROR":
    raise Exception(f"Something went wrong: {notification.text}")
```

## Authenticating in your account

To authenticate in your account, you must provide a valid API-KEY and API-SECRET:
```python
bfx = Client(
    [...],
    api_key=os.getenv("BFX_API_KEY"),
    api_secret=os.getenv("BFX_API_SECRET")
)
```

## Error:
Traceback (most recent call last):
  File "...\main_2.py", line 77, in <module>
    notification: Notification[Order] = bfx.rest.auth.submit_order(
  File "...\lib\site-packages\bfxapi\rest\_interfaces\rest_auth_endpoints.py", line 120, in submit_order
    *self._m.post("auth/w/order/submit", body=body)
  File "...\lib\site-packages\bfxapi\rest\_interface\middleware.py", line 82, in post
    data = request.json(cls=JSONDecoder)
  File "...\lib\site-packages\requests\models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "...\lib\site-packages\simplejson\__init__.py", line 533, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "...\lib\site-packages\bfxapi\_utils\json_decoder.py", line 16, in __init__
    super().__init__(*args, **kwargs, object_hook=_object_hook)
TypeError: JSONDecoder.__init__() got an unexpected keyword argument 'encoding'

### Python version
Python 3.10.14

**Comment by gorchakov** [comment]
arrow==1.3.0
attrs==24.3.0
bitfinex-api-py==3.0.4
bitmex==0.2.2
bravado==11.0.3
bravado-core==6.1.1
certifi==2024.12.14
charset-normalizer==3.4.1
contourpy==1.3.0
cycler==0.12.1
fonttools==4.55.3
fqdn==1.5.1
idna==3.10
importlib-resources==6.4.5
isoduration==20.11.0
jsonpointer==3.0.0
jsonref==1.1.0
jsonschema==4.23.0
jsonschema-specifications==2024.10.1
kiwisolver==1.4.7
matplotlib==3.9.4
monotonic==1.6
msgpack==1.1.0
mysql-connector-python==9.1.0
numpy==2.0.2
packaging==24.2
pillow==11.0.0
pyee==11.1.1
pyparsing==3.2.0
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
pytz==2024.2
PyYAML==6.0.2
referencing==0.35.1
requests==2.32.3
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpds-py==0.22.3
simplejson==3.19.3
six==1.17.0
swagger-spec-validator==3.0.4
types-python-dateutil==2.9.0.20241206
types-requests==2.31.0.20240406
types-urllib3==1.26.25.14
typing-extensions==4.12.2
uri-template==1.3.0
urllib3==2.3.0
webcolors==24.11.1
websocket-client==1.8.0
websockets==12.0
zipp==3.21.0
