### ISSUE TITLE
Failed authentication after reconnect

### ISSUE THREAD

**Issue by Mnogoidey** [bitfinexcom/bitfinex-api-py#50]
Hello,

Some times i get error "asyncio:Fatal error on SSL transport", after that reconnection is initialized. But, if I trying put new order I get authentication error.

Error: (socketId=0) Failed authentication - auth: invalid

SSL transport error:

[BfxOrderManager] [INFO] Update Order order_id=37344025432 dispatched
ERROR:asyncio:Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0548CD18>
transport: <_ProactorSocketTransport fd=1160 read=<_OverlappedFuture pending overlapped=<pending, 0x7182de8> cb=[_ProactorReadPipeTransport._loop_reading()]> write=<_OverlappedFuture finished result=31> write_bufsize=117>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\asyncio\sslproto.py", line 698, in _process_write_backlog
    del self._write_backlog[0]
IndexError: deque index out of range
ERROR:websockets.protocol:Error in data transfer
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\websockets\protocol.py", line 674, in transfer_data
    message = yield from self.read_message()
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\websockets\protocol.py", line 742, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\websockets\protocol.py", line 815, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\websockets\protocol.py", line 880, in read_frame
    frame = yield from Frame.read(
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\websockets\framing.py", line 99, in read
    data = yield from reader(2)
  File "C:\Program Files (x86)\Python38-32\lib\asyncio\streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "C:\Program Files (x86)\Python38-32\lib\asyncio\streams.py", line 517, in _wait_for_data
    await self._waiter
  File "C:\Program Files (x86)\Python38-32\lib\asyncio\sslproto.py", line 698, in _process_write_backlog
    del self._write_backlog[0]
IndexError: deque index out of range
[BfxWebsocket] [ERROR] WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
[BfxWebsocket] [INFO] Waiting 5 seconds before retrying...

My code for new order:
 bfx = Client(
        API_KEY=API_KEY,
        API_SECRET=API_SECRET,
        logLevel='INFO'
    )
@bfx.ws.on('authenticated')
    async def handle_events(self):
        while True:

                    if up_order.eid is False:
                        
                        response = await bfx.ws.submit_order(pair, up_order.price, up_order.quantity,
                                                             up_order.order_type, up_order.hidden,
                                                             gid=up_order.gid)
                    else:
                        
                        response = await bfx.ws.update_order(up_order.eid, price=up_order.price,
                                                             amount=up_order.quantity, hidden=up_order.hidden)

**Comment by ph4z** [comment]
Most of the time these errors occurs when you try to read and write on the socket at the same time.
Try to set a [lock](https://docs.python.org/3/library/asyncio-sync.html#asyncio.Lock) before writing to ws

**Comment by JacobPlaster** [comment]
Yep you are correct @ph4z. This issue was fixed in the PR https://github.com/bitfinexcom/bitfinex-api-py/pull/45
