### ISSUE TITLE
example get authenticated endpoints does not work

### ISSUE THREAD

**Issue by jonatan-klock** [bitfinexcom/bitfinex-api-py#60]
#### Issue type
- [x] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
the example get rest authenticated endpoints produces an error

#### Steps to reproduce
Traceback (most recent call last):
  File "trade/bitfinex_api_py/get_authenticated_data.py", line 63, in <module>
    asyncio.get_event_loop().run_until_complete(t)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "trade/bitfinex_api_py/get_authenticated_data.py", line 57, in run
    await log_active_positions()
  File "trade/bitfinex_api_py/get_authenticated_data.py", line 38, in log_active_positions
    positions = await bfx.rest.get_active_position()
  File "/home/jklock/crypto/env/lib/python3.5/site-packages/bfxapi/rest/bfx_rest.py", line 259, in get_active_position
    return [Position.from_raw_rest_position(rp) for rp in raw_positions]
  File "/home/jklock/crypto/env/lib/python3.5/site-packages/bfxapi/rest/bfx_rest.py", line 259, in <listcomp>
    return [Position.from_raw_rest_position(rp) for rp in raw_positions]
  File "/home/jklock/crypto/env/lib/python3.5/site-packages/bfxapi/models/position.py", line 41, in from_raw_rest_position
    return Position(*raw_position)
TypeError: __init__() takes 11 positional arguments but 21 were given

##### Additional Notes:
- I use the bitfinex-api-py (1.1.4)

**Comment by JacobPlaster** [comment]
Thanks, fixed in https://github.com/bitfinexcom/bitfinex-api-py/issues/63, please try again
